### ISSUE TITLE
zipArchiveDidUnzipFileAtIndex:totalFiles:archivePath:fileInfo: doesn't provide filename

### ISSUE THREAD

**Issue by shortstuffsushi** [soffes/ssziparchive#101]
The delegate method, zipArchiveDidUnzipFileAtIndex:totalFiles:archivePath:fileInfo: returns a unz_file_info struct, but no way to determine what the name of that file was (from what I can tell). The method actually has a reference to it (strPath / fullPath), but doesn't expose this to the delegate.

Is there a different way to obtain this? To actually use the unz_file_info, I'd need the zipFile struct as well, which is also not exposed.

**Comment by Rostmen** [comment]
I have the same problem

**Comment by istx25** [comment]
I will look into this.

**Comment by shortstuffsushi** [comment]
Thanks guys :smile:
