### ISSUE TITLE
Unzipping succeeds if the password is wrong

### ISSUE THREAD

**Issue by milkllc** [soffes/ssziparchive#110]
I zipped an archive with a password using `zip -er` in Mac OS. In my app I was able to unzip it with the password. As a test I also tried unzipping with a nil password and it did not report a failure. My app only crashed when it tried to parse the unzipped data. 

Should `unzipFileAtPath:toDestination:overwrite:password:error:` return `NO` and an error if the password is incorrect?

**Comment by wimbledon** [comment]
I confirm this problem as well!

**Comment by istx25** [comment]
I will look into it.

**Comment by istx25** [comment]
I believe this issue has been fixed.

**Comment by istx25** [comment]
Everything is working perfectly for me. Unzipping does not succeed if the password is wrong.
