### ISSUE TITLE
Unable to Append to Zipfile

### ISSUE THREAD

**Issue by lauzilla** [soffes/ssziparchive#116]
Hello
First of all thanks for writing this library. I was using it today and it works fine to create many Zip files. But as soon as I want to append to an existing Zipfile it doesnt work. Instead of appending to the existing Zipfile a new one is created and the old one is overwritten. How do I properly append to a Zip file using SSZiparchive? I need this as the order of the files in my Zip-archive matters. Thanks for any help

**Comment by istx25** [comment]
Was this ever solved?

**Comment by dustturtle** [comment]
Why this issue closed without any explaination? I got the same problem now. Please help.
