### ISSUE TITLE
How to archive empty folder in other folder?

### ISSUE THREAD

**Issue by DimonDeveloper** [soffes/ssziparchive#125]
I have folder with files and empty folders, but ssziparchive don't archive empty folder.
How to fix it?

**Comment by istx25** [comment]
Have you figured out what was wrong, @DimonDeveloper?

**Comment by DimonDeveloper** [comment]
Yes, and i sended code to Sam Soffes, but he is not added it to git.

**Comment by istx25** [comment]
Awesome! If you could fork and create a PR with the related improvements, that would be much appreciated.

**Comment by DimonDeveloper** [comment]
@istx25 I add two PR, I did it the first time, I do not know whether they added.

**Comment by istx25** [comment]
#135
