### ISSUE TITLE
CocoaPods version

### ISSUE THREAD

**Issue by watershade-apps** [soffes/ssziparchive#140]
https://cocoapods.org/?q=ssziparchive

have pod 'SSZipArchive', '~> 1.0'
should be set to pod 'SSZipArchive', '~> 0.2.1'

**Comment by istx25** [comment]
I have zero experience with setting up/maintaining CocoaPods...Would you be able to fix this, @soffes?

**Comment by ddebin** [comment]
The repository lacks a `0.3.3` tag as specified in the `.podspec` file, breaking CocoaPods.
