### ISSUE TITLE
Can't find CollectingDelegate.h file 

### ISSUE THREAD

**Issue by K-Be** [soffes/ssziparchive#141]
I've tried to run tests, but can't find file CollectingDelegate.h

**Comment by fish2000** [comment]
I had the same problem – if you are curious and/or antsy, you can find versions of CollectingDelegate in the repo from like 2012 here: 
https://github.com/soffes/ssziparchive/tree/67403e8a283676787fcd07843aade0137452a04f/Tests
… YMMV, they needed a few edits to get working (e.g. one or two `#if !__has_feature(objc_arc)`’s and the like).

**Comment by soffes** [comment]
Bummer looks like that file is missing. Can you fix this @istx25?

**Comment by istx25** [comment]
I was investigating some of the old commits and I'm not sure I understand what the purpose of this class is? Is CollectingDelegate.h a test or a fixture?

**Comment by dimohamdy** [comment]
fixed,please Accept pull request
