### ISSUE TITLE
Pod file

### ISSUE THREAD

**Issue by trungnguyen1791** [soffes/ssziparchive#149]
Please can you guys update the pod file? 
Currently this pod version is not latest version.

Thanks

**Comment by soffes** [comment]
What do you need from me, @istx25?

**Comment by istx25** [comment]
I'm sorry, but like I mentioned in #140. I have zero experience with CocoaPods and would love it if you (or someone else) could manage the CocoaPods side. :person_frowning:

**Comment by adamyanalunas** [comment]
The `.podfile` is pointing to the `0.3.2` tag, which is latest. @trungnguyen1791 what updates are you looking for? I have plenty of CocoaPods familiarity and will help out if I'm able.
