### ISSUE TITLE
SIGTRAP when ziping a directory on the commandline

### ISSUE THREAD

**Issue by jk** [soffes/ssziparchive#26]
I tried to extract a zip file which I've crafted using the standard linux zip command by do so:

```bash
zip -q -r commandline-version.zip index.json web/
```

When I try to extract it with
```ObjC
[SSZipArchive unzipFileAtPath:@"commandline-version.zip" toDestination:dest];
```

it ends up in a SIGTRAP. **EDIT:** Before it ends up in a SIGTRAP there are some files extracted.

So I was curious and tried several things when creating the zip file. All variations of the `zip` command weren't honored with any success. But when I zip the files in Finder.app with its archive action from the context menu, the extraction within iOS succeeded.

Any ideas?

I uploaded the both zip files in question:
* commandline-version.zip (the failing one): http://cl.ly/HuHZ
* finder-version.zip (the working one): http://cl.ly/HuCk

PS: I use SSZipArchive via its CocoaPods podspec.

**Comment by istx25** [comment]
Has this issue been fixed @jparishy?

**Comment by istx25** [comment]
Has this issue been fixed @jparishy?

**Comment by istx25** [comment]
I'm having a hard time replicating this problem. I believe it has been fixed sometime in between Jul 7, 2012 and now.
