### ISSUE TITLE
Create zip with password protection

### ISSUE THREAD

**Issue by klapaudius** [soffes/ssziparchive#29]
Hello

It would be great if we could have a method like :
+ (BOOL)createZipFileAtPath:(NSString *)path withFilesAtPaths:(NSArray *)filenames overwrite:(BOOL)overwrite password:(NSString *)password;

Thanks

**Comment by bokic** [comment]
I have made patch with pull request regarding creating password protected zip

https://github.com/soffes/ssziparchive/pull/124

**Comment by istx25** [comment]
#110

**Comment by Coeur** [comment]
Available at least since version 1.1 of ZipArchive.
Note that ZipArchive 2.1 made AES optional for compatibility with Archive Utility and other tools.
