### ISSUE TITLE
Modification dates are wrong when creating a zip using SSZipArchive

### ISSUE THREAD

**Issue by somalenny** [soffes/ssziparchive#35]
Creating a zip on an iPad using SSZipArchive, then transferring it to a Mac and unzipping it in the OS X finder, produces files with the modification date : 30 Nov 1979 00:00.

I realise that writeFile:path doesn't fill in any date info, but shouldn't I be seeing : 31 Dec 1979 00:00 ?  (i.e. 1 Jan 1980.)  It looks like it's off by a month.

If I modify writeFile:path to read the file's modification date and pass this into the call to zipOpenNewFileInZip(), then when I unzip on OS X, I get dates that are 1 hour later than the original files (although I did encounter one file that retained the correct date/time).

Ie changing :

	zipOpenNewFileInZip(_zip, [[path lastPathComponent] UTF8String], NULL, NULL, 0, NULL, 0, NULL, Z_DEFLATED, Z_DEFAULT_COMPRESSION);

to

	NSError* error = nil;
	NSDate* fileDate;
	NSDictionary* attr = [[NSFileManager defaultManager] attributesOfItemAtPath:path error:&error];
	if (error == nil && attr) {
		fileDate = (NSDate *) [attr objectForKey:NSFileModificationDate];
	} else {
		fileDate = [NSDate date];
	}
	zip_fileinfo zipInfo = {{0,0,0,0,0,0},0,0,0};
	[self zipInfo:&zipInfo setDate:fileDate];
	zipOpenNewFileInZip(_zip, [[path lastPathComponent] UTF8String], &zipInfo, NULL, 0, NULL, 0, NULL, Z_DEFLATED, Z_DEFAULT_COMPRESSION);

However, if I explicitly put [NSDate date] into zipInfo, I get the correct, current date (not offset by an hour).

Am I doing something wrong, or is there an underlying problem ?

tia
Lenny.

**Comment by istx25** [comment]
Have you figured out what was wrong, @somalenny?

**Comment by istx25** [comment]
Fixed.
