### ISSUE TITLE
Path inclusive #include "minizip/unzip.h" breaks CocoPod 

### ISSUE THREAD

**Issue by levigroker** [soffes/ssziparchive#37]
It would seem the #include "minizip/unzip.h" breaks in 2.2.3 when used as a CocoaPod. The podspec says:

    s.preserve_paths = 'minizip'

But the header search path in the Pods.xcconfig remains simply "${PODS_ROOT}/BuildHeaders/SSZipArchive" and the "${PODS_ROOT}/BuildHeaders/SSZipArchive" directory is flat.

Changing the include to:

    #include "unzip.h"

solves the issue, for me.

**Comment by levigroker** [comment]
I assume this is closed because it is fixed? Thanks!

**Comment by istx25** [comment]
Yup.
