### ISSUE TITLE
fileIsSymbolicLink == YES when should be NO

### ISSUE THREAD

**Issue by kts** [soffes/ssziparchive#52]
I was just testing this out and it was crashing on a zip file I was using.  After further inspection, it was setting fileIsSymbolicLink to YES.  I'm not sure if I am doing something else wrong, but if I just manually set it to NO, it unzips properly.

The zip file is at this URL (207MB):

http://archive.org/download/um2013-04-13.ck950.flac24/um2013-04-13.ck950.flac24_vbr_mp3.zip

**Comment by istx25** [comment]
Please create a PR with the related improvements. (@kts @nms666 @abretucorazon)

**Comment by istx25** [comment]
Fixed.
