### ISSUE TITLE
Zipping removes file modes (e.g. executable) on files

### ISSUE THREAD

**Issue by SquaredTiki** [soffes/ssziparchive#60]
When zipping up a folder or bundle containing files which have specific file modes set such as being executable, these file modes are lost.

For example when zipping a `.app` file the executable in the MacOS sub directory is no longer executable and thus the app cannot be launched.

**Comment by istx25** [comment]
Did you ever figure out what was wrong, @SquaredTiki? Was it included in #63?

**Comment by SquaredTiki** [comment]
Yes it was indeed resolved in #63, should have closed this previously.

**Comment by istx25** [comment]
Sweet. Thanks for your contribution!
