### ISSUE TITLE
Potential thread issue for zipping large or multiple files

### ISSUE THREAD

**Issue by aceisScope** [soffes/ssziparchive#70]
I came across this recently, and really don't know where to look into. The situation I use SSZipArchive is like this:  in app's documents directory there's a folder with several audio file within, all in .aac format. I need to zip the audio files and upload the zip file onto a server. 
At first I simply used `[SSZipArchive createZipFileAtPath:zippedPath withFilesAtPaths:inputPaths]` (every time it returns a YES) and then upload; later I noticed the zip file might fail to contain the correct amount of audio files, i.e. originally 7 audio files, after zipping, only 3 or 4 or sometimes even nothing zipped.  
So I run a test with NSOperationQueue to zip 100 times in the same situation, and when it comes to the 26th or 27th (not always, but somewhere around), the zip file will fail to contain all the 7 audio files.

**Comment by istx25** [comment]
Fixed.
