### ISSUE TITLE
UNZ_BADZIPFILE after resumed a file download, despite file being ok.

### ISSUE THREAD

**Issue by helloniklas** [soffes/ssziparchive#74]
So, I'm using AFDownloadRequestOperation to download a zip file. This works fine. But, if network connection drops, then come back on again, it refused to unzip the file giving a UNZ_BADZIPFILE. Howeever, if I manually go in and check the device tmp dire the downloaded zip file is there and I can copy it to desktop and unzip it on my Mac, so file does seem to be correct.

Any ideas?

**Comment by istx25** [comment]
Have you figured out what was wrong, @helloniklas / @oscarvgg?

**Comment by istx25** [comment]
From what I've see (in my own testing), this bug has been fixed. Not sure if this was fixed by someone in the `SSZipArchive` community, or if this was a problem with `AFDownloadRequestOperation`.
