### ISSUE TITLE
problems for very large archives

### ISSUE THREAD

**Issue by dbquarrel** [soffes/ssziparchive#75]
I need to unpack an archive which is very large in size, both number of files and the count of files. Overall the zip is 1.8 gigs with 26,000 files in it. 

Some suggestions:

1. you need to use an @autoreleasepool {} structure in your main loop while you're yanking the individual files out of the zip. Otherwise all of the autoreleased objects that you're using will collect up on the main autorelease pool and the memory use will spiral out of control. Using this structure do { @autoreleasepool { } } while(i++ < 100000) has a much smaller memory footprint since it will nuke all of the autoreleased objects on each iteration. So I suggest you put those in.

2. The mutable set directoriesModificationDates collects up all kinds of objects and then performs all of its actions at the end of the execution of the main loop. Again, in a mobile environment if you do this and someone encounters an archive like this (rare, but still), the set will just explode with objects causing the memory footprint to spiral way up. It is better instead to set the attributes on the fly as the objects are created, rather than collect them up into a set for processing later. This will keep your memory footprint with a known upper bound. 

Both of these together implemented will mean you can process a zip archive of infinite size without ever causing the OS to nuke your process for excessive memory use. As is there are limits and SSZipArchive will get you nuked. Now, probably almost nobody will hit those limits... but I did. Might as well code it with no limits.

The side benefit is it's faster too than tracking everything in a datastructure for changing later.

Further suggestions:

Similarly this code constantly calls [self class] to get the class object to call a class method. Placing this call once at the top:

class myClass = [self class]

Will in my case save something like 100,000 method calls. Tiny mods do a lot in a mobile environment.

Oh and also for delegates, rather than check every time you send a method whether or not they implement it, its better to check once, set a flag, and use that flag to make the call.

**Comment by istx25** [comment]
Was this ever solved? (@dbquarrel @tnys @soffes)

**Comment by istx25** [comment]
@dbquarrel A PR is still welcome! :smiley:

**Comment by dbquarrel** [comment]
Sorry, I don't use github very much. I put the fix up, I assumed it would be 
integrated.

**Comment by istx25** [comment]
Okay, thanks @dbquarrel!

**Comment by NasH5169** [comment]
I'm reading this issue but my english skill cannot permit me to understand if this improvement was added to the current version of ZipArchive ? I'm using some huge archive with 10000+ files inside.

Thanks for helping me to understand :)

**Comment by dbquarrel** [comment]
Yes, it was folded in.

**Comment by NasH5169** [comment]
For now, i have just turned off the modification date on the last version and the decompression time with a 45000 files archive droped from 25 minutes to 5 minutes :-)

**Comment by dbquarrel** [comment]
Hmm, well I don't know entirely what was done in the end with my additions, it 
sounds like whomever put my fixes in place only put the autorelease pool in. 
That's important to stop it from exploding when dealing with large archives but 
the file modification fix improves performance considerably. Possibly that 
change was ignored. I am not folding my changes in directly but just submitted 
it here. But if the code I submitted was used verbatim then you wouldn't have 
the performance issue as far as I understand it (I had the performance issue 
too, which is why I put the fix forward, I am dealing with archives of about 
35,000 items).
