### ISSUE TITLE
Modification Dates

### ISSUE THREAD

**Issue by l3nko** [soffes/ssziparchive#78]
Hi,
thanks you for work.
I would tell you about a problem, during unzip a very high number of files (~3000) the set directoriesModificationDates will have a big size that cause some problem and slow unzip process. 
I've commented the rows where you add the modification date of every path and it has became more fast.
So you can try to set modification date at one folder for time or not set it, it's not realy useful, the creation date remain the orginal date. 

Best regards,
l3nko

**Comment by istx25** [comment]
Please create a PR with the related improvements. Thanks!

**Comment by istx25** [comment]
#35
