### ISSUE TITLE
Detect if zip has a passcode?

### ISSUE THREAD

**Issue by MaxHasADHD** [soffes/ssziparchive#80]
All my zips i just unzip but how do i check if it has a passcode? Will SSZipArchive detect it and ask for the password? Zips are downloaded from the internet so I don't know if they has a passcode and only want to ask for one from user if it does

**Comment by istx25** [comment]
Please submit a pull request that fixes the issue with tests. Thanks!

**Comment by istx25** [comment]
Related: #29

**Comment by Coeur** [comment]
Done by #258 in ZipArchive 1.3
