### ISSUE TITLE
Not Unzipping Files > 2 GB

### ISSUE THREAD

**Issue by PranavJaiswal** [soffes/ssziparchive#81]
I'm trying to Unzip a file over 2GB (2.69 GB Precisely).
I'hv implemented the following method to unzip File;

+ (BOOL)unzipFileAtPath:(NSString *)path toDestination:(NSString *)destination delegate:(id<SSZipArchiveDelegate>)delegate;

[SSZipArchive unzipFileAtPath:sourcePath toDestination:destinationPath delegate:self];
Which returns NO. 

I Debugged the problem & found out that I Get the UNZ_BADZIPFILE in function unzOpenInternal(). I cross checked with the zip file & its unzipping correctly.
I'm stuck, Please let me know how do I get this working. A quick response will be highly valuable & appreciable.

**Comment by istx25** [comment]
Was this ever solved?
