### ISSUE TITLE
Can't UnArchive file small than 74 byte

### ISSUE THREAD

**Issue by feng20068** [soffes/ssziparchive#87]
You can create a txt just with one word "Hello",then Archive it to 1.zip,ssziparchive can't unArchive it.

**Comment by istx25** [comment]
Please create a PR with the related improvements. Thanks!

**Comment by dimohamdy** [comment]
I test it with 5 byte Archive file and it's unArchive it ,without any problem

please accept my pull request that have a test of this case

**Comment by istx25** [comment]
In #154.
