### ISSUE TITLE
the function unzipFileAtPath doesn't extract the content  of zip file

### ISSUE THREAD

**Issue by lorenagaido** [soffes/ssziparchive#89]
Hi,
when running the function :

  BOOL success = [SSZipArchive unzipFileAtPath:filePathToUnzip toDestination:destinationPath overwrite:YES password:nil error:&errzip];

it returns YES , and no error found. but the file isn't present in the destination folder

I've tried to manually download, and unzip  the file  from PC, wihout problems: thus the file isn't corrupted

I think the issue is related to the "symbolic link"

has anyone experienced this issue before?

thanks
Lorena

**Comment by istx25** [comment]
Please create a PR with the related improvements. Thanks!

**Comment by lorenagaido** [comment]
The problem did not occur more, and now I do not have a project where it occurs. Thank you

**Comment by istx25** [comment]
Sweet.
