### ISSUE TITLE
Empty folder not Ziping

### ISSUE THREAD

**Issue by Niraj91** [soffes/ssziparchive#93]
I want to zip empty folder but not it not working...

**Comment by DimonDeveloper** [comment]
I changed the method createZipFileAtPath for zip empty folder, not a perfect solution but it's better than nothing.

+ (BOOL)createZipFileAtPath:(NSString *)path withContentsOfDirectory:(NSString *)directoryPath {
    BOOL success = NO;

    NSFileManager *fileManager = nil;
	SSZipArchive *zipArchive = [[SSZipArchive alloc] initWithPath:path];

	if ([zipArchive open]) {
        // use a local filemanager (queue/thread compatibility)
        fileManager = [[NSFileManager alloc] init];
        NSDirectoryEnumerator *dirEnumerator = [fileManager enumeratorAtPath:directoryPath];

		NSString *fileName;
        while ((fileName = [dirEnumerator nextObject])) {
            BOOL isDir;
            NSString *fullFilePath = [directoryPath stringByAppendingPathComponent:fileName];
            [fileManager fileExistsAtPath:fullFilePath isDirectory:&isDir];
            if (!isDir) {
                [zipArchive writeFileAtPath:fullFilePath withFileName:fileName];
            }
            else
            {
                if([[NSFileManager defaultManager] subpathsOfDirectoryAtPath:fullFilePath error:nil].count == 0)
                {
                    NSString *tempName = [fullFilePath stringByAppendingPathComponent:@".DS_Store"];
                    [@"s" writeToFile:tempName atomically:YES encoding:NSUTF8StringEncoding error:nil];
                    [zipArchive writeFileAtPath:tempName withFileName:[fileName stringByAppendingPathComponent:@".DS_Store"]];
                    [[NSFileManager defaultManager] removeItemAtPath:tempName error:nil];
                }
            }
        }
        success = [zipArchive close];
	}

#if !__has_feature(objc_arc)
    [fileManager release];
	[zipArchive release];
#endif

	return success;
}

**Comment by soffes** [comment]
Can you send a pr with your fix and a test? Thanks!

**Comment by soffes** [comment]
Cc @DimonDeveloper

**Comment by DimonDeveloper** [comment]
Here is a project with tests of these functions. Sorry if something is not done so, I am new to this.
