### ISSUE TITLE
Nested .zip files

### ISSUE THREAD

**Issue by nsands** [soffes/ssziparchive#98]
I need to be able to recursively unzip nested zip files (i.e., zip files containing zip files and the inner zip files should be unzipped in place removing the original inner zip file).

I've achieved this with the below code.  It's rather crude but does the job for me.  If anybody else wants to take this on and improve it and incorporate it into the project that would be great.

WITHIN METHOD:

	+ (BOOL)unzipFileAtPath:(NSString *)path toDestination:(NSString *)destination overwrite:(BOOL)overwrite password:(NSString *)password error:(NSError **)error delegate:(id<SSZipArchiveDelegate>)delegate {

IMMEDIATELY AFTER:

	if (fp) {
		...
	}

INSERT CODE:

	//  RECURSIVELY UNZIP NESTED .zip ZIP FILES AND DELETE THE UNZIPPED NESTED .zip FILES
				
	if ( [[[fullPath pathExtension] lowercaseString] isEqualToString:@"zip"] )
	{
		NSLog(@"Unzipping nested .zip file:  %@", [fullPath lastPathComponent]);
					
		if ( [self unzipFileAtPath:fullPath toDestination:[fullPath stringByDeletingLastPathComponent] overwrite:overwrite password:password error:nil delegate:nil] )
		{
			[[NSFileManager defaultManager] removeItemAtPath:fullPath error:nil];
		}
	}

**Comment by istx25** [comment]
Please create a PR with the related improvements. Thanks!

**Comment by nsands** [comment]
Sorry, but I don't know the first thing about Git or pull requests.  Besides, my code is very crude and rudimentary.  If people want to use it, they can, or if somebody else wants to do a PR, then again, they are welcome to do so.

**Comment by istx25** [comment]
Fixed.

**Comment by Coeur** [comment]
I changed the default behavior to NOT unzip nested zip files, but allow to do it with the nestedZipLevel parameter starting with ZipArchive 2.1.
